### ISSUE TITLE
Not grouping by date for me, and text is white by default

### ISSUE THREAD

**Issue by darkvertex** [boukestam/inbox-in-gmail#1]
I want to love this extension, and the screenshots look like pretty much what I'd want.

However I tried it today and it's not very usable. I think some of the styling broke, and tried changing different inbox modes but it's not grouping by date like I saw in the screenshots.

What can I do to help you debug this? This is what I'm getting: (Some personal areas I pixelized, but it's pretty much as-is.)

![screenshot from 2019-02-01 10-02-05](https://user-images.githubusercontent.com/941331/52130672-d2382700-2608-11e9-9082-57a8beb1fa5e.png)

I'm on Google Chrome on Linux (CentOS) with `Version 71.0.3578.98 (Official Build) (64-bit)`

ps: It would be nice if you would eventually begin using the Github "releases" feature in this repo, so people can click the "watch" eyeball (beside the star) set to "Releases only" and see when this gets updated and improved.

**Comment by boukestam** [comment]
Hi, 

Thanks a lot for the information. At my side everything still looks fine, so it's maybe a different version of gmail or something else is interfering.

Are there maybe some other extensions that are interfering with the styling?
If not, could you send a snapshot of the HTML of some of the elements that look wrong? You can do this in the debugger, if you just select the tabs for example you don't send any personal data. Inspect the element, select it in the debugger, than right click => copy => copy outer html

I'll also look into the github releases. That could certainly be useful.

**Comment by darkvertex** [comment]
> Are there maybe some other extensions that are interfering with the styling?

I don't really use any extensions that affect styling of pages and beyond my favourite adblocker (uBlock Origin), my extensions don't really "edit" pages either, and I have it disabled for Gmail since their ads don't annoy me.

I went a step further, opened an incognito window, enabled your extension to work in incognito (it's a setting you can turn on for all extensions that is off by default.) This greatly reduced the number of active extensions down to a few popular non-styling ones: Lastpass, Session Buddy, uBlock Origin (with Gmail whitelisted, so disabled) and ClutterFree (prevents duplicate tabs, doesn't style or edit them.)

This leads me to believe it's not an extension sabotaging it.

My guess is I have some peculiar Gmail settings enabled that you don't and the extension can't make sense of and it's tripping it at some point.

I'm sorry can you get more specific about the steps for copying "outer html"? I opened the Developer Tools (I guess that's what you meant by "debugger"?), clicked the top left icon in it to "inspect" one of the illegible rows of mail but then I don't know where the "copy outer html" menu is. Rightclicking inside Gmail just shows me its own rightclick actions (to deal with the email) so I guess I must do it somewhere in the Developer Tools window? But not sure where. Pardon my ignorance.

By the way, opening the Developer Tools did let me spot an uncaught exception in your 
 extension, maybe that's why it's breaking:

![screenshot from 2019-02-01 11-31-46](https://user-images.githubusercontent.com/941331/52136133-64dec300-2615-11e9-976e-61eb591d9e11.png)

Hope some of this helps.

**Comment by boukestam** [comment]
Thanks for making sure it's not a problem with another extension.

I've fixed the error you saw in a new version, it should be up in an hour or. If it doesn't download automaticly you can update in the chrome://extensions page. I'm not sure if that fixes the styling problem, if it doesn't you can copy the HTML in the "Elements" tab of the chrome developer tools. Having the html of the effected sections could help me pinpoint the problem.

![image](https://user-images.githubusercontent.com/8492132/52167700-9348c500-271f-11e9-98d2-f7ebb4deab58.png)

Thanks a lot for giving me this much information

**Comment by darkvertex** [comment]
I checked my browser's extension version and it was on 0.3.5 which seems to be the latest you speak of.

I have some good news and some bad news. Let's start with the good news... date grouping works now. :) Bad news... still virtually all white and can't read a thing in the UI. lol

Here's some `outerHTML` copied from an all-white email row, if it helps:

```html
<tr class="zA zE btb byw" jsaction="bjyjJe:NOSeAe;pInidd:NOSeAe;" jscontroller="ZdOxDb" jsmodel="nXDxbd" id=":3d" tabindex="0" aria-labelledby=":3e" draggable="true"><td class="PF xY PE"></td><td id=":3f" class="oZ-x3 xY" style=""><div id=":3g" class="oZ-jc T-Jo J-J5-Ji " role="checkbox" aria-labelledby=":3e" dir="ltr" aria-checked="false" tabindex="-1"><div class="T-Jo-auh"></div></div></td><td class="apU xY"><span id=":3h" class="aXw T-KT" title="Not starred" aria-label="Not starred" role="button"><img class="T-KT-JX" src="images/cleardot.gif" alt="Not starred"></span></td><td class="WA xY" jsaction="crxiQe" jscontroller="v9XiUc"><div class="pG" data-tooltip-contained="true" data-tooltip-align="b,l" data-tooltip-delay="1500" aria-label="Not important" role="img" id=":3i"><div class="T-ays-a45"><span class="aol">Click to teach Gmail this conversation is important.</span></div><div class="pH-A7 a9q"></div><div class="bnj "></div></div></td><td class="yX xY "><div id=":3e" class="afn">unread, Tenshi .. Steven 13,Re: Creating a valley in Softimage - Ideas, has attachment, 2:36 PM, Anyone? On Sat, Dec 15, 2018, 12:44 Tenshi &lt;tenshi.cg@gmail.com wrote: Guys! Need your Softimage expertise and advices here. In a few weeks from now, at my job, i will began creating a scene that.</div><div id=":3j" class="yW"><span class="bA4"><span class="zF" email="tenshi.cg@gmail.com" name="Tenshi" data-hovercard-id="tenshi.cg@gmail.com" data-hovercard-owner-id="21">Tenshi</span><span class="yP"> .. </span><span class="zF" email="carons@gmail.com" name="Steven" data-hovercard-id="carons@gmail.com" data-hovercard-owner-id="21">Steven</span></span> <span class="bx0">13</span></div></td><td id=":3k" tabindex="-1" class="xY a4W"><div class="xS" role="link"><div class="xT"><div class="y6"><span id=":3m" class="bog"><span class="bqe" data-thread-id="#thread-f:1620038887176030624" data-legacy-thread-id="167b88c8d87249a0" data-legacy-last-message-id="168ba02b12347a6f" data-legacy-last-non-draft-message-id="168ba02b12347a6f">Re: Creating a valley in Softimage - Ideas</span></span></div><span class="y2"><span class="Zt">&nbsp;-&nbsp;</span>Anyone? On Sat, Dec 15, 2018, 12:44 Tenshi &lt;tenshi.cg@gmail.com wrote: Guys! Need your Softimage expertise and advices here. In a few weeks from now, at my job, i will began creating a scene that</span></div></div><div class="brd" role="list" jscontroller="tnECjd"><span class="bzB">Attachment</span><div class="brc" data-index="0" tabindex="0" title="captur.PNG" role="listitem" jsaction="lkS8Jd"><img class="brf" aria-hidden="true" src="//ssl.gstatic.com/docs/doclist/images/mediatype/icon_1_image_x16.png" srcset="//ssl.gstatic.com/docs/doclist/images/mediatype/icon_1_image_x32.png 2x"><span class="brg">captur.PNG</span></div><div class="bre brc" role="listitem" jsaction="gWgFib" tabindex="0" title="1 more attachment"><span class="brg" aria-label="1 more attachment" role="button">+1</span></div></div></td><td class="byZ xY"></td><td class="yf xY "><img class="yE" src="images/cleardot.gif" title="Has attachment" alt="Has attachment"></td><td class="xW xY "><span title="Mon, Feb 4, 2019, 2:36 PM" id=":3n" aria-label="Mon, Feb 4, 2019, 2:36 PM"><span class="bq3">2:36 PM</span></span></td><td class="bq4 xY"><ul class="bqY" id=":3o" role="toolbar"><li class="bqX brq" data-tooltip="Archive" jsaction="JqEhuc" jscontroller="pk1i4d"></li><li class="bqX bru" data-tooltip="Delete" jsaction="zM6fo" jscontroller="pmCKac"></li><li class="bqX brr" data-tooltip="Mark as read" jsaction="aUd46b" jscontroller="VtSflc"></li><li class="bqX brv" data-tooltip="Snooze" jsaction="u4Fnue" jscontroller="PKSrle"></li></ul></td></tr>
```

**Comment by boukestam** [comment]
The html classes match with what I have, so that can't be the problem.
I've managed to replicate the problem though, by switching to the dark theme.
This makes all text white.

![image](https://user-images.githubusercontent.com/8492132/52330213-24a48980-29f5-11e9-98a0-d0b3627c573e.png)

You can change the theme back to normal under settings => themes.
Could you check if that is the problem?

**Comment by darkvertex** [comment]
Yay! That was it!! :smile: I switched to the Default theme and I can read everything.

I can live with setting leaving the theme at Default for now, though if your extension can somehow adapt to recognize dark themes and style accordingly, that'd be great of course.

Worst case scenario if you can at least add a mention in the extension description and README that it only works with the Default theme, then it'll be less of a surprise to others. :+1:

Thank you for your time investigating this.

**Comment by boukestam** [comment]
Nice! I'll make sure to add it to the description, thats a good idea.
I'll also think about a dark theme, that is a nice addition.
Thanks a lot for helping me fix this bug!
