### ISSUE TITLE
Today, yesterday and monthly views no longer showing

### ISSUE THREAD

**Issue by naughtiboi** [boukestam/inbox-in-gmail#110]
Hey guys, 

This extension has been working really well for me the last couple years!
Thanks for keeping it up and running.

Unfortunately, the Today, Yesterday and Monthly grouped views in the mail inbox column are no longer showing. The current appearance is all of the messages in a line going straight downwards, similar to Gmail's current layout.

I think the html coding might have changed in gmail to cause the layout to stop functioning.

Can someone please have a look at this?

Many thanks,
Naughtiboi

**Comment by joeytroy** [comment]
@naughtiboi this repo is no longer maintained. It's been moved to
 https://github.com/team-inbox/inbox-reborn

It's also approved on the Chrome store as well. There is a bug for this same issue we are working through as well.

**Comment by naughtiboi** [comment]
Thanks a lot for the heads up. :)
