### ISSUE TITLE
Compose button disappears when I use the side bar

### ISSUE THREAD

**Issue by joeytroy** [boukestam/inbox-in-gmail#13]
![image](https://user-images.githubusercontent.com/1558465/55676135-5ae27600-588b-11e9-87fc-b16f0bea0e31.png)

**Comment by russelldc** [comment]
More reason to get rid of the right side bar 😈Just kidding (mostly...)

**Comment by joeytroy** [comment]
lol fixed https://github.com/inbox-in-gmail/inbox-in-gmail/commit/0772e62a49de0271a092882d49cf8cd04dfb8429
