### ISSUE TITLE
Chrome Web Store has outdated screenshot

### ISSUE THREAD

**Issue by russelldc** [boukestam/inbox-in-gmail#14]
The screenshot should be updated to better represent the current state of the UI

**Comment by boukestam** [comment]
Fixed! The new screenshot should be showing up in about an hour or so. Here it is already:
![inbox v0 4 4](https://user-images.githubusercontent.com/8492132/55909834-3bc24c00-5bdd-11e9-95cf-3655c67c5a7f.png)

I'm not great at marketing so if anyone has any suggestions you can add screenshots to the screenshot folder and I'll add them as well in next releases.
