### ISSUE TITLE
Click to toggle on/off not working after cookie set

### ISSUE THREAD

**Issue by SharonPerp** [boukestam/inbox-in-gmail#15]
The click that toggles the extension on and off only works the first time I use it. Then it will work again when I delete all the gmail cookies, which obviously defeats the purpose.

Fantastic extension though, life changing since Inbox died. Thank you!

**Comment by russelldc** [comment]
@SharonPerp Could you explain more? As far as I'm aware, this extension does not have an on/off toggle.

**Comment by SharonPerp** [comment]
Wow, I figured it out and it's really great. Sometimes I like to switch
back to regular gmail to work with colored labels. The problem was, I
wasn't refreshing after clicking. This screenshot should help:

[image: image.png]

**Comment by SharonPerp** [comment]
Oh, boo, it only worked the first time again. It's really great when it
works. :-(

**Comment by SharonPerp** [comment]
So, sorry to spam you, but I guess it's not really the toggle I thought it
was. I guess it just enables it on gmail the one time. Wonder if I could
block that one cookie if it would toggle back and forth when refreshing...?

**Comment by SharonPerp** [comment]
Last spam, I promise! I found a decent work around.

When I close gmail it reset, even without dealing with cookies. So, before
clicking, I opened a second gmail tab and only clicked on the first tab so
it's Inbox in Gmail and the second tab is classic Gmail.

Not sure what would happen if I refreshed  second tab, but I think it will
be fine for me as often as I need to use classic.

Really enjoying your app now!

**Comment by russelldc** [comment]
Haha, I still have no idea what you're talking about, exactly. It looks like your screenshot wasn't uploaded properly, it just says ' [image: image.png]'

**Comment by russelldc** [comment]
If you're talking about going to the Extensions page of the Chrome browser settings, and disabling this extension, that should work 100% of the time. This extension isn't interacting with cookies. When you disable any Chrome extension, you need to refresh the relevant tab (Gmail, in this case) to see the changes.

**Comment by russelldc** [comment]
Could you also explain the colored labels that's keeping you attached to classic Gmail? Perhaps we can integrate them into the extension.

@g60madman , is that related to the colored star tags you were working on fixing?

**Comment by joeytroy** [comment]
I would need to see a screen shot of what is going on. Based on what I am hearing is it a tab issue on top for social, promostion, ect? Or are we talking labels that have color coating? If you could publish a screen shot that would great.

**Comment by joeytroy** [comment]
@SharonPerp can you post a screenshot of the before and after?

**Comment by SharonPerp** [comment]
Sorry, I've been really busy. I'll try to clear some of this up.

Here are the colored labels (the four at the bottom). They're on the
sidebar, I don't use the tabs:

[image: image.png]

Here is what your extension icon looks like on the Chrome bar the first
time I open Gmail. Notice it has a circle around it?

[image: image.png]

When I click on it the first time after opening Gmail, I get this:

[image: image.png]

BECAUSE, I had changed this setting below, earlier. The default appears to
be "On mail.google.com" I liked the idea of being able to toggle it so I
switched it to "When You Click the Extension":

[image: image.png]



Here's what extension icon looks like after I click on it:
[image: image.png]
Once I've clicked on it the first time there is no toggle. It just stays in
Inbox in Gmail until the next time I open Gmail (or the next tab I open
Gmail in, which was the handy workaround I discovered.)

I hope that's helpful. I don't mean to be a pain and I really appreciate
all the hard work you're doing on this!

Sharon

**Comment by SharonPerp** [comment]
One last thing. I was busy and stressed today and just realized I've been
inadvertently and inappropriately using classic gmail this whole day.

So, omg, just went back to Inbox in Gmail and it's freaking AMAZING! I just
can not believe how relaxing it is. Great great great job! <3 <3 <3

**Comment by joeytroy** [comment]
@SharonPerp the images are not coming through at all? All you need to do is copy and paste in the window and they will show up correctly. Right now I am just seeing [image: image.png]. Also glad you are enjoying Inbox in Gmail it's really coming together thanks to so many developers all working together!

**Comment by SharonPerp** [comment]
Yeah, copy/paste is exactly what I did. So, here it all is in an attached
pdf.

And, after my realization of how HORRIBLE gmail classic is compared to your
app, I'm probably not even going to bother with those colored labels
anymore. Love your interface too darn much!

:-)

**Comment by russelldc** [comment]
@SharonPerp I think you're trying to add attachments to an email, which isn't going to show on GitHub. You'll need to visit this page directly to do so.

**Comment by SharonPerp** [comment]
Yikes, had no idea this was all public. Hope I didn't say anything untoward. And, hope this works this time...

[Inbox in Gmail.pdf](https://github.com/boukestam/inbox-in-gmail/files/3069606/Inbox.in.Gmail.pdf)

**Comment by joeytroy** [comment]
@SharonPerp it make sense about the color labels. I am sure we can do something as I have the same issue

Gmail
![image](https://user-images.githubusercontent.com/1558465/55973745-6e069480-5c43-11e9-97ad-401d4eb90d5e.png)

Inbox in Gmail Extension Enabled
![image](https://user-images.githubusercontent.com/1558465/55973825-8d9dbd00-5c43-11e9-9472-b73fe253870d.png)

It maybe possible to add this feature since it does show the background color based on the label
![image](https://user-images.githubusercontent.com/1558465/55973940-d35a8580-5c43-11e9-818b-70eed32461d7.png)

I will see what I can do with this.

**Comment by SharonPerp** [comment]
That would be great. Then no reason at all to go to classic, ugh, it's such
a disaster.

Thanks!

**Comment by joeytroy** [comment]
@SharonPerp I did a small hack and basically threw a border around the boxes so they show up with the proper color people have on Gmail. If you think this looks good and @russelldc think it looks alright I can merge it into the code.

![image](https://user-images.githubusercontent.com/1558465/55976390-4b777a00-5c49-11e9-9123-70e5bf325dca.png)

`/* Category */
.aHS-bnr .qj {
	background-image: url("https://i.ibb.co/wCh8tQ9/ic-custom-cluster-24px-g60-r3-2x.png") !important;
	background-repeat: repeat-x;
	padding: 13px;
	width: 48px;
	length: 48px;
	border: 3px solid #F2F2F2;
  box-sizing: border-box;
}`

**Comment by russelldc** [comment]
Well I guess a question for @SharonPerp is:

I don't use labels, so I just want to make sure... are you just concerned with the label colors on the left menu, or are there also colored labels on the emails themself?

**Comment by joeytroy** [comment]
@russelldc 

Here is some screens from gmail
![image](https://user-images.githubusercontent.com/1558465/55977147-4a474c80-5c4b-11e9-9de4-ccb8dfbd9fc3.png)

![image](https://user-images.githubusercontent.com/1558465/55977116-356ab900-5c4b-11e9-9c67-38ed7f9c3b9a.png)

And with the extension on and my mod
![image](https://user-images.githubusercontent.com/1558465/55977179-63e89400-5c4b-11e9-9f23-231f168585c2.png)

![image](https://user-images.githubusercontent.com/1558465/55977116-356ab900-5c4b-11e9-9c67-38ed7f9c3b9a.png)

**Comment by russelldc** [comment]
@SharonPerp @g60madman Never mind, I answered my own question. The colored labels in the email list are working fine already.

**Comment by russelldc** [comment]
@g60madman I see now, after adding my own labels.

I'd recommend adding a border-radius: 30% as well. It looks like this, a little less abrasive:

<img width="247" alt="Screen Shot 2019-04-11 at 6 21 38 PM" src="https://user-images.githubusercontent.com/5100126/55977432-af6c6380-5c86-11e9-9422-a58f4d8eafd4.png">

**Comment by joeytroy** [comment]
@russelldc  Good call! 
![image](https://user-images.githubusercontent.com/1558465/55977661-98108480-5c4c-11e9-8636-7a42ba70b834.png)

`/* Category */
.aHS-bnr .qj {
	background-image: url("https://i.ibb.co/wCh8tQ9/ic-custom-cluster-24px-g60-r3-2x.png") !important;
	background-repeat: repeat-x;
	padding: 12px;
	width: 48px;
	length: 48px;
	border: 3px solid #F2F2F2;
  box-sizing: border-box;
	border-radius: 30%;
}`

Should I push it up or wait for @SharonPerp to respond?

**Comment by russelldc** [comment]
I'm fine with pushing now

**Comment by joeytroy** [comment]
Done https://github.com/inbox-in-gmail/inbox-in-gmail/commit/83348af3d803125c4a3fc287910be2542561c8b6

**Comment by SharonPerp** [comment]
Sorry, busy day, I concur that the radius makes it work just right. Thanks!

**Comment by joeytroy** [comment]
@SharonPerp sounds good, If you want to close this out since I don't have permission.
