### ISSUE TITLE
Dark Mode is not working

### ISSUE THREAD

**Issue by joeytroy** [boukestam/inbox-in-gmail#16]
Thank you so much for the Add-on. Unfortunately the font describing my mails seems to be the same color as the background and thus the messages are unreadable until opened (Sadly I can't attach a screenshot). It might have something to do with Chrome's dark mode?

**Comment by theRealPadster** [comment]
Do you have the dark theme selected in Gmail? I had that problem and had to change it back to default.

**Comment by joeytroy** [comment]
@theRealPadster another user posted this on the support forum so I added it to the github board. It's listed as a bug right now and needs to be looked at. I haven't had time to look at issues for a while been busy with other projects.

**Comment by russelldc** [comment]
@g60madman @theRealPadster Yeah, I just tried out Dark Mode on MacOS / Chrome, and it doesn't affect the page at all. That user must have just had Gmail's dark theme enabled.

**Comment by joeytroy** [comment]
I'll close it out.
