### ISSUE TITLE
Sun background image displays at the bottom of Search results

### ISSUE THREAD

**Issue by russelldc** [boukestam/inbox-in-gmail#20]
@g60madman I'm seeing the sun image show up on search results, whenever there's more than one page of results.

<img width="1680" alt="Screen Shot 2019-04-08 at 3 31 29 PM" src="https://user-images.githubusercontent.com/5100126/55732206-81331d80-5a13-11e9-8486-6f0ddbcc388e.png">

**Comment by russelldc** [comment]
Sometimes it looks like this, which may be a better hint as to what's causing it:

<img width="1680" alt="Screen Shot 2019-04-08 at 3 33 55 PM" src="https://user-images.githubusercontent.com/5100126/55732365-c48d8c00-5a13-11e9-8058-502ee593c9ee.png">

**Comment by joeytroy** [comment]
@russelldc check out this commit, it fixes most of the issues. If you feel it's good go ahead and close it out.

https://github.com/inbox-in-gmail/inbox-in-gmail/commit/05ce3ac3d71876e57e2bd6e18b2f440006bfc423

**Comment by russelldc** [comment]
I'm seeing this ugly text now, I don't remember it being there in the previous commits:

<img width="558" alt="Screen Shot 2019-04-10 at 7 27 51 PM" src="https://user-images.githubusercontent.com/5100126/55904018-ccd9f880-5bc6-11e9-91a7-153e7d1628af.png">

**Comment by russelldc** [comment]
@g60madman Doesn't seem like it fixed the problem I was reporting. I'm still seeing the Sun at the bottom of every page of my search results:

<img width="949" alt="Screen Shot 2019-04-10 at 7 36 48 PM" src="https://user-images.githubusercontent.com/5100126/55904575-1840d680-5bc8-11e9-8611-51e4a7a650cc.png">

**Comment by joeytroy** [comment]
@russelldc I added back the text. So the problem is when you search it's adding the TD and TC tags, which is the same tags when email is empty. If you search for a two letter search like "bob barker" it adds an extra tag "eb TD" so I can hide the sun there. I guess we would need to write some java to hide it which is out side of my skill set.  Also I added back the text incase people want to see as it was leaving the "view messages".

**Comment by russelldc** [comment]
@g60madman Ahh, got it. In that case, I'll try changing the way the sun background image is displayed/added to the empty inbox. As you could tell, I'm not a fan of the text overlaying the sun, haha.

Unimportant side note: I noticed you've mentioned Java a few times recently. In case you're not aware, JavaScript is unrelated to Java, they have just stupidly similar names.

**Comment by russelldc** [comment]
@g60madman Mind if I merge latest master of this repo into the team inbox org's repo?

**Comment by joeytroy** [comment]
@russelldc yeah I know its JS I just keep saying java to save on typing script I will put JS for now lol. Yeah go forth and push. Ideally I think it might be easiest to work out of one repo. I created the team so we would all have permissions. What ever is easiest for everyone is good for me.

**Comment by russelldc** [comment]
@g60madman I pushed a fix to the inbox-in-gmail/inbox-in-gmail repo, let me know if it works for you.

**Comment by joeytroy** [comment]
@russelldc perfect!

**Comment by russelldc** [comment]
Closing, since it'll be fixed when @boukestam merges the PR
