### ISSUE TITLE
Available to firefox

### ISSUE THREAD

**Issue by maoanran** [boukestam/inbox-in-gmail#24]
Thanks for the extension! is it possible to make the extension to be available in firefox?

I don't know how many efforts do we need, but I guess it should be not so much.

**Comment by russelldc** [comment]
I tried loading it as an unpacked extension into Firefox, and it worked as expected.

@boukestam would just need to pack and deploy to the [Firefox Add-ons Store](https://addons.mozilla.org/en-GB/firefox/)

**Comment by russelldc** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Distribution/Submitting_an_add-on

**Comment by boukestam** [comment]
@maoanran I have published the extension to the firefox add-on store: https://addons.mozilla.org/nl/firefox/addon/inbox-in-gmail/ 

Let me now if you find any unexpected bugs

**Comment by maoanran** [comment]
Thank you guys! it works!
