### ISSUE TITLE
Large blank space above Inbox email list when using 'Unread First' or 'Starred First' inbox types

### ISSUE THREAD

**Issue by russelldc** [boukestam/inbox-in-gmail#25]
Related to the recently merged PR #12 authored by @abasiri 

I was incorrect in my comment on that PR. The new commit did not fix the top padding/spacing issue. It temporarily went away because I switched from the 'Unread First' or 'Starred First' inbox type to the 'Default' inbox type.

With the latest code, and the 'Unread First' or 'Starred First' inbox type, that large space is still present.

<img width="1680" alt="Screen Shot 2019-04-07 at 1 36 01 AM" src="https://user-images.githubusercontent.com/5100126/55676886-868a4e00-58d5-11e9-81ca-438daf870ce8.png">

**Comment by russelldc** [comment]
Actually, this is even happening on the Default inbox type, for my wife's account. Though I'm not sure why yet.

**Comment by abasiri** [comment]
Sorry to hear that. I'll take a look tonight. If you can inspect and see
which class is causing the passing, that would really help as I can't repro
on my account.

**Comment by abasiri** [comment]
I have a repro. I'll submit a fix for it soon.

**Comment by boukestam** [comment]
Fixed in https://github.com/boukestam/inbox-in-gmail/pull/36
