### ISSUE TITLE
Add toggle in extension options to hide Hangouts & the right-side tools menu

### ISSUE THREAD

**Issue by russelldc** [boukestam/inbox-in-gmail#28]
Found this in the User Reviews on the Chrome web store:

> The only thing's i'd like to see changed is the hangouts block in the menu, I'd like to see it gone and the new google menu on the right. It is a bit glitchy and is not aligned with anything

I'd previously made a PR to remove them, but I think a good compromise could be made here:

Add a toggle to hide Hangouts & the right-side menu in the extension's options/right click dropdown menu.

**Comment by boukestam** [comment]
The hangouts block can already be removed by going to Settings -> Chat -> Chat off. The right side menu can also be toggled at the bottom

**Comment by russelldc** [comment]
Ah I wasn't aware you could turn off Hangouts completely, I thought you could only log out.
