### ISSUE TITLE
Completely hide left menu rather than just shrink it

### ISSUE THREAD

**Issue by russelldc** [boukestam/inbox-in-gmail#29]
Found this in the User Reviews on the Chrome web store:

> Liking it quite a bit so far! Though I do feel like the left menu should be fully hidden when you close it to match even closer to Inbox.

We'll need to sort out a way to still keep the Compose button visible when the left menu is hidden.

**Comment by joeytroy** [comment]
I agree, lets get rid of it 👍

**Comment by boukestam** [comment]
We could redo the compose button like how the reminder button works. Just hide the original and add a new element which triggers the original compose button when pressed.

**Comment by russelldc** [comment]
Yep, that might somehow make it easier to control its position when the task sidebar is open, as well.

**Comment by russelldc** [comment]
Clicking the new Compose button element could trigger [`gmail.compose.start_compose()` via the Gmail.js lib](https://github.com/KartikTalwar/gmail.js#gmailcomposestart_compose)

**Comment by russelldc** [comment]
Fixed in commit https://github.com/boukestam/inbox-in-gmail/commit/2ca70b7828e1faf2f8db6bdc0dab5716fdb42ada
