### ISSUE TITLE
Improve description on Chrome web store

### ISSUE THREAD

**Issue by russelldc** [boukestam/inbox-in-gmail#31]
Found this in the Support section on the Chrome web store:

>Overview should mentions the options to turn off to get best results
>Hi, thanks for the extension, it's really useful and makes gmail a tons better. However, I add to dig a few options in gmail to get the look that the video shows, so i think you should document those on the Overview page so that people don't get confuses 
>- Use the default Theme 
>- Disable in Settings/Advanced: 
>   * Chat on the Right
>   * Multiple Inbox

It looks like @boukestam has already added the 'No Dark Theme' advice to the Overview/Description, but it may be best to explicitly tell them to use the Default theme.

Chat on the Right might be fixed my myself soon, so no need to point that out, but I do think it'd make sense to mention that they'd get the best results by disabling the tabbed email categories, among other things:

Settings/Inbox/Categories -> Leave only Primary ticked
Settings/Inbox/Importance markers -> No Markers
Settings/Inbox/Inbox Type -> Default or Starred First
Settings/Advanced/Multiple Inbox -> Disabled
Settings/Advanced/Preview Pane -> Disabled

**Comment by boukestam** [comment]
Good idea, I'll add that to the description. Except for importance markers since that should be fixed now.
