### ISSUE TITLE
New code load breaks top bar

### ISSUE THREAD

**Issue by joeytroy** [boukestam/inbox-in-gmail#40]
If you click on any of the circled area's they do not work. I am using the code from 

https://github.com/inbox-in-gmail/inbox-in-gmail

![image](https://user-images.githubusercontent.com/1558465/55911604-3560af80-5b9e-11e9-8dca-6948c8ae2c37.png)

**Comment by russelldc** [comment]
Oof, this is a big one. This is occurring on this main fork too, and the chrome web store version.

**Comment by joeytroy** [comment]
@russelldc wonder if Google just edited some code because this was working this morning.

**Comment by russelldc** [comment]
@g60madman Nah, it's working fine when I rollback to earlier commits. Trying to figure out now which commit started it.

**Comment by russelldc** [comment]
@boukestam @g60madman This started happening on commit 7a8f570e9f3cc1a3020b801e86db172ae3deb863 'Firefox version'

In Firefox, there's no issue with this change, but Chrome does not appreciate it.

**Comment by joeytroy** [comment]
@boukestam @russelldc, who uses Firefox anyways? lol I say tell em to use a real browser that doesn't need special css to work.

**Comment by russelldc** [comment]
@boukestam I actually don't understand what that css is supposed to fix. I tried loading the latest code into Firefox, with those Firefox-related lines removed, and I'm not seeing any issues.

**Comment by russelldc** [comment]
I've included removal of this css to my existing hot-fix PR #38

**Comment by gnowland** [comment]
The menu positioning and z-index are also broken. Submitting a PR.

![Screen Shot 2019-04-10 at 4 25 47 PM](https://user-images.githubusercontent.com/4430119/55915912-d492a080-5bb8-11e9-9d49-95a611782b34.png)

**Comment by russelldc** [comment]
If this 'Firefox version' CSS for some reason necessary (didn't seem like it in my testing)... it could be set to activate on Firefox only. This seems to work:

```css
@-moz-document url-prefix() {
    blahblahblah
    blahblahblah
}
```
