### ISSUE TITLE
Date bundling snoozed emails

### ISSUE THREAD

**Issue by byronigoe** [boukestam/inbox-in-gmail#48]
When snoozed emails come back to the inbox, the date bundling operates on the original date of the thread. See the attached screenshot which shows Today, This month, Yesterday, Today, Yesterday, This month.

![image](https://user-images.githubusercontent.com/10134042/55972174-4235df80-5c40-11e9-86ea-5af9322a0e73.png)

**Comment by russelldc** [comment]
Hey @byronigoe :

In case you missed it, @abasiri has a potential solution for this problem waiting in a PR.
