### ISSUE TITLE
Message list and view have different widths

### ISSUE THREAD

**Issue by Muffo** [boukestam/inbox-in-gmail#49]
From the message list (i.e. the main view) when you open message the width of the white box with the content will considerably increase, assuming that your monitor is wide enough.

Like the original Inbox, it would be nice to preserve the width of the list view also for the messages.

**Comment by joeytroy** [comment]
@Muffo do you have a screen shot? I think this may have already been fixed.

**Comment by russelldc** [comment]
@g60madman [![Image from Gyazo](https://i.gyazo.com/97e3a3a0e99779d925602156b84cbf55.gif)](https://gyazo.com/97e3a3a0e99779d925602156b84cbf55)

**Comment by joeytroy** [comment]
Done I believe if  @Muffo and  @russelldc could verify

https://github.com/inbox-in-gmail/inbox-in-gmail/commit/ef4c3a50a586ab0209545b9093c8329601ebc3c0

**Comment by joeytroy** [comment]
Added another commit to add some clean margins.

https://github.com/inbox-in-gmail/inbox-in-gmail/commit/0fa6d64e294b34dd4fe4274ee70ff862401ee46d

**Comment by russelldc** [comment]
@g60madman Seems to be performing mostly as expected now, except the opened email is just ever so slightly wider compared to the list

**Comment by joeytroy** [comment]
@russelldc noticed that just now. I will bring it down.

**Comment by joeytroy** [comment]
@russelldc alright think I got it
https://github.com/inbox-in-gmail/inbox-in-gmail/commit/608c60706699e76d08ec2e62dd9edf22b66fcbd8

**Comment by russelldc** [comment]
@g60madman I noticed the toolbar up above the email looks a little odd being no longer aligned to the width of the email below it. It's a little trickier to fix, moving the tools on the left side of it to line up with the email, while keeping the tools on the right side (like the settings cog) aligned to the right of the screen.

**Comment by Verniax** [comment]
I agree with @russelldc. The toolbar with the square should ideally be vertically aligned with the square in the email below. They sort of belong together.

**Comment by joeytroy** [comment]
@Verniax @russelldc little hack but it slaps the tool bar in the center. I tried to add some padding but it caused more issues if the resolution is low.

![image](https://user-images.githubusercontent.com/1558465/55988516-4d4d3780-5c61-11e9-8c67-868d30b1b60e.png)

`/* email tool bar */
.iH.bzn{
	margin-left:auto !important;
	margin-right:auto !important;
}`

**Comment by russelldc** [comment]
In my opinion, that looks a lot worse than just leaving it 😃 

I think I might have a solution.

**Comment by joeytroy** [comment]
This is a little closer

`/* email tool bar */
.iH.bzn{
	margin-left:auto !important;
	margin-right:auto !important;
	width: 1px;
}`
Plugin
![image](https://user-images.githubusercontent.com/1558465/55988997-7fab6480-5c62-11e9-8f73-d8fb8c554fdb.png)

Old inbox
![image](https://user-images.githubusercontent.com/1558465/55989026-9356cb00-5c62-11e9-9bd6-d3f601189ada.png)

**Comment by russelldc** [comment]
I pushed up my solution, it aligns the entire toolbar with the email. I tested at many different screen widths, seems to work out well.

https://github.com/inbox-in-gmail/inbox-in-gmail/commit/4c3e95fba50b644cea25b610188933ee3b25e5fe

<img width="708" alt="Screen Shot 2019-04-11 at 9 07 29 PM" src="https://user-images.githubusercontent.com/5100126/55989718-de420400-5c9d-11e9-806d-0b5ebe6d2bf9.png">

**Comment by joeytroy** [comment]
@Muffo you can close this one up.

**Comment by Muffo** [comment]
Thanks for the quick fix!! Looking forward to the new release
