### ISSUE TITLE
Small rectangular grey area covering parts of the side bar title

### ISSUE THREAD

**Issue by Verniax** [boukestam/inbox-in-gmail#50]
![inbox1](https://user-images.githubusercontent.com/49449648/55980191-3a078f80-5c94-11e9-9ae2-bc6a11ceeceb.JPG)

**Comment by joeytroy** [comment]
@Verniax fixed

**Comment by russelldc** [comment]
@g60madman Yeah, that's the same fix I did locally last time I noticed this problem. I'm not sure what that line of css was meant to fix, I don't see an issue with the compose box after removing it.

**Comment by joeytroy** [comment]
@russelldc got it fixed.

**Comment by russelldc** [comment]
@g60madman I know :P I was referring to the changes you made. I don't know if there's any negative side effects from commenting out that css.

**Comment by russelldc** [comment]
@g60madman Here's what the css you commented out affects:

[![Image from Gyazo](https://i.gyazo.com/5a2b0cf0686e20bef4c32e8f8aaa7693.gif)](https://gyazo.com/5a2b0cf0686e20bef4c32e8f8aaa7693)

Without that css, the compose box (when minimized or not) will be slightly behind the compose/reminder buttons, except when a task bar item like Google Keep is open.

**Comment by joeytroy** [comment]
@russelldc yeah, I am sure there is a better fix then messing with the .no id. I added that fix way back when.

**Comment by russelldc** [comment]
Yeah, the .no class is used often throughout Gmail

**Comment by joeytroy** [comment]
@russelldc got it

https://github.com/inbox-in-gmail/inbox-in-gmail/commit/392949fa98a8ec83d8db21a5b19bfa6ddcaa85e9

**Comment by russelldc** [comment]
Perfect, I don't see anything else with that combination of classes on the page

**Comment by joeytroy** [comment]
Nor I. 

@Verniax you can close this one up.

**Comment by Verniax** [comment]
Awesome! Thanks.
