### ISSUE TITLE
Every email sent to myself shows as a reminder

### ISSUE THREAD

**Issue by russelldc** [boukestam/inbox-in-gmail#6]
According to the description on the Chrome Web Store:

> It shows all emails sent to yourself with subject "Reminder" as reminders inside your inbox.

Instead, it's doing this for every email, not just those with "Reminder" in the subject.

**Comment by SharonPerp** [comment]
And on mine, it doesn't show the actual reminder, just a blank subject field.

**Comment by abasiri** [comment]
@SharonPerp PR #12 also fixes the missing subject field for reminders.

**Comment by SharonPerp** [comment]
Thanks!

**Comment by russelldc** [comment]
This also makes the 'Sent' folder look weird. When I open that folder, about a third or more of the emails look like reminders, even when they weren't sent to me from myself. And if I open any of those emails, then click the inline Back button, they become Reminders (labeled with the Reminder icon).

**Comment by abasiri** [comment]
I also find this annoying. Since there are varying opinions on this, one option would be to have an extension preferences tab and have this as a toggle option.

**Comment by abasiri** [comment]
I decided to take a crack at it in #61

**Comment by russelldc** [comment]
Solved by @abasiri 's PR #61 awaiting approval by @boukestam
