### ISSUE TITLE
Change Favicon

### ISSUE THREAD

**Issue by Perifractic** [boukestam/inbox-in-gmail#60]
Small thing but it would be nice if you could change the Favicon too 👍

**Comment by russelldc** [comment]
@Cjsnet Certainly very doable! This line can be run from the `script.js` on initialization:

`document.querySelector('link[rel*="shortcut icon"]').href = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAC4AAAAuCAMAAABgZ9sFAAAA8FBMVEVHcExGbcdPds/h4eJCas01r/BVe9KCz/R/m9PY2+E/acxGbs9af9Ta290wS4x/zPXt7e9HabqYor1dt+wvU6zp6ehEar40WK1Gabfv7u3R1d1Oaaexv95iw/E6su6Bz/SBzfOE1fsxufY0uvY7ZMs4Yco1X8k9btjl5eTj4+NAcdlCc9o1u/gwWrcuV7EnR5c9Z82B0/kvuPcoTaktU6MvVqsnSqBYfs8zXrzJz988d9aqttIlRI85kOBIccu6wtVrzPdEvvV4wfBAbcJvi9A4n+c+gttioN1FXZdYxfZciNJ/l9V/ja5tr+gnQoZUkt+J5e8pAAAAIXRSTlMAq3f96P1Kvw/9+s4oiP76FJH9c+ilUdMpUjv9v8CwwLBmLZScAAACG0lEQVRIx43SaXeaQBQGYFywqFm0Jt3bdFhGoEalqGisZtGaxqTp//83vZcZYIBBec/x2zN33juiKLI0ut2GUjZatW5Z9apWTp9UWhaltFU5KaMbbdNCTq12VKjzsXOoiMU85YU6l7VTrbCIlXgTC3UuHUfuG+2xKXJK2w3ttOY4TvOTrIhpZjitfwl1fjoUMfP8uSnXWMRMfKTls6HIWMLZ7Jeulisy5lwsw/XrWeVDtgjX6yDhW9S1l9dfo9H7d+kX4U3Wy+aWci7o0ewiKsRfhGvHZh61DfrtWahnsykrFL8IZluzHXuxB0/3i5T2fR8LwTeSaJzugA8oDVA7ovb9i6oSflExtzbcyzR45Wacznppow/1EnRkh5iNoq5u3B9C3OAWPf6Wf0aTyWQ6HF5D5vP55vFcGQzUneBdtx96nM0046CDB0KAD4zf8QWuG3n7Nq03jx5hHC5YuS6zyNGn9fV8D6ORG8YgvGDXjzX4RVqv/3ok4uwArswx+s+ChhUJETg7ASv349BppMMVsxxPwMqJN6dMsxUlHKKuBA9/S7yinBviBaawYhHHlSPfSlYs4njBjul/DyQXRdczWtd1vGCX7RFxPTmh86gr2eiYZ3N/55HS3HgqwDJu3N8RUpoX9pDxAz0k/FCPHD82GvnPUiuyeMDDHFuRac/jvEQPxlWcfbwH0+dKTy03OtQ9Ret9+/qmVK6+97T/W3MEXFqJ8TYAAAAASUVORK5CYII="`

This could obviously be changed to a link to an image hosted within the extension, if that Base64 data uri is too ugly/unwieldy. Either way, I'll make a PR with this change, or just update my existing one, #56 

This even updated the icon on my bookmarks bar when I tested it out. 👍
