### ISSUE TITLE
Top Bar Changes colour and text when Composing 

### ISSUE THREAD

**Issue by pdarmas** [boukestam/inbox-in-gmail#80]
Hello there, firstly **thank you** for this extension, you have done a fantastic job and could not thank you guys enough for bringing this back to life! 

Now I don't know if is intended but when composing an email with or a "pop out reply" the top changes colour to grey instead of the usual blue and displays "Search" instead of Inbox. See below: 

![Inbox Bug_censored](https://user-images.githubusercontent.com/50215689/57568962-8571a280-73e6-11e9-8c4c-41c1b82f2f7b.jpg)

**Comment by russelldc** [comment]
Definitely not intended, thanks @pdarmas 

I'll probably fix this myself, today. It's an issue with the URL hash changing when the compose popup is opened.

**Comment by russelldc** [comment]
@pdarmas Fixed in latest commit, 525c01aea5edf20e81a1775478a85aa87ab5c89b
