### ISSUE TITLE
Publish update for Firefox?

### ISSUE THREAD

**Issue by jcgoble3** [boukestam/inbox-in-gmail#81]
While the mess in #69 with the Chrome store is going on, the Firefox add-on store listing has been neglected. The last version available on the Firefox add-on store predates the introduction of label bundles, which is why I am still using the temporary add-on method from a git clone.

Can someone please package up the current version and publish an update for Firefox? That would benefit anyone who uses this in Firefox. It looks like the Chrome issues will quite possibly take a while to resolve, and it doesn't make sense to limit the experience for Firefox users due to a Chrome policy issue.

**Comment by jcgoble3** [comment]
Bump. Pinging @boukestam here; it's been a month with no replies. Can we please, *please* get an update published for Firefox? It is painful having to manually load the extension as a debugging extension every time I restart Firefox, and now that I am using a portable version of Firefox as well on school computers, it's even more painful since I sometimes restart that copy up to a dozen times a day when I log out of a computer without easy access to the extension's source code.

My email is completely unusable with the version in the Firefox add-on store, and this extension is critical to my ability to function. Please upload a new version, or else I may be forced to create my own AMO account and upload it myself, because I cannot continue manually reloading the extension a dozen times a day. I don't want to do that, but if you don't publish it yourself, I may have no other choice.

**Comment by boukestam** [comment]
Thanks for letting me know. I was very bummed out because of the removal from the chrome store so I kinda of forgot about firefox and took a break from development of the extension in general. I have just uploaded a new version to firefox so it should be up in about an hour. Please let me know if there are any problems, I have only tested the general features

**Comment by jcgoble3** [comment]
Thanks. I've been using the HEAD of master, so this seems to be the same. This will make it much easier to handle my email.
