### ISSUE TITLE
Grey instead of blue

### ISSUE THREAD

**Issue by LLI-inc** [boukestam/inbox-in-gmail#86]
I just downloaded the latest version from here on github and installed it. The frames around the message index (on my 2-column layout) are grey, instead of blue.  Only if I use version 0.4.7 are they blue. 0.5.0 and 0.5.1 make them grey.

![image](https://user-images.githubusercontent.com/46686069/61976179-0c332600-afb9-11e9-816e-33f4313fef2b.png)

**Comment by russelldc** [comment]
Would you want it to be blue, or to be the normal lighter gray background color?

We don't "officially" support the 2-column/preview pane layout right now, it's recommended in the setup instructions/readme to disable it.

**Comment by russelldc** [comment]
@LLI-inc I just pushed up a commit to master to remove those background colors that were inadvertently placed behind the email list in vertical split mode. It looks like this now:

<img width="1920" alt="Screen Shot 2019-08-01 at 4 00 59 PM" src="https://user-images.githubusercontent.com/5100126/62304573-1dc37480-b476-11e9-9e2e-82438c5dd3c3.png">

**Comment by LLI-inc** [comment]
Love the blue / hate the grey!  Thanks for the word on the 2-column layout. It has worked fine for me though. Your revision looks great. I'll install it sometime today.  Thanks so much!  

Jonathan.

**Comment by russelldc** [comment]
No problem. By setting the background to invisible, instead of to a specific color, it means you'll be able to see the background color or photo if you set a theme. There's other unsolved issues related to themes (mostly just text/icon colors), but... thinking ahead!

**Comment by russelldc** [comment]
@LLI-inc I cut a release, in case you didn't want to build it yourself:

https://github.com/boukestam/inbox-in-gmail/releases/tag/0.5.2
