### ISSUE TITLE
Set my email on the from field when creating a new reminder

### ISSUE THREAD

**Issue by arormoser** [boukestam/inbox-in-gmail#87]
When you have multiple email address on your Gmail account and your main email is not the default one, the reminder is created under the default email address and should be created with the main email address. To fix that on line 448 of script.js you need to add this:

const from = document.querySelector("input[name='from']");
from.value = myEmail;

**Comment by russelldc** [comment]
@arormoser  When I was looking into fixing this just now, suddenly I'm noticing not even my To field is getting filled... is that part broken for you too, or is it just me?

**Comment by russelldc** [comment]
I noticed you mentioned line 448 of script.js, it seems like you're on an outdated version. In the current master branch, this logic happens around line 766: https://github.com/boukestam/inbox-in-gmail/blob/master/src/script.js#L766

**Comment by arormoser** [comment]
Yes, you are right. I was on an outdated version.

**Comment by russelldc** [comment]
Locally I fixed the issue that was blocking my To field from being filled, by changing the querySelector here from `.gb_db` to `.gb_lb`:

```javascript
const getMyEmailAddress = () => document.querySelector('.gb_lb') ? document.querySelector('.gb_lb').innerText : '';
```

Pushing up the change now, along with your request for the From field.
