### ISSUE TITLE
Grey background with white icons. Almost unreadable

### ISSUE THREAD

**Issue by maikol-solis** [boukestam/inbox-in-gmail#97]
Hi! 

Awesome add-on, however the colors palette seems a little awkward with the grey and white colors. Please change it for the new gmail. 

![image](https://user-images.githubusercontent.com/4078489/75072575-59c73100-54bd-11ea-9e9a-e41b8b726763.png)

Thanks.

**Comment by jcgoble3** [comment]
It seems you have the dark theme set in Gmail. Unfortunately, this extension only works correctly with the default theme.

**Comment by maikol-solis** [comment]
Yes, I see. Thanks for the clarification. I changed it to the default theme.
